from __future__ import annotations

DEFAULT_PERTURB_RATIO = 0.8
DEFAULT_PERTURB_WORKERS = 4
PERTURBED_BILL_SCHEMA_VERSION = 1
PERTURBED_OUTPUT_SUFFIX = "_perturbed"
PERTURBATION_MANIFEST_FILENAME = "perturbation_manifest.json"
PERTURBATION_DEMOGRAPHIC_MAX_ATTEMPTS = 3
PERTURBATION_LINE_ITEM_CODE_SYSTEMS = ("HCPCS/CPT",)
PERTURBATION_COMPONENT_CODE_SYSTEMS = (
    "APR-DRG",
    "DRG",
    "ICD10_PCS",
    "MS-DRG",
    "REVENUE_CODE",
)
